NoTLS option #minor
neicnordic/sda-mq pull request #21
Opened 2021-11-29 10:44 UTC by jbygdell

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [X] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

### Changes made:

1) Updated the docker image to use 3.8.16
2) updated the config semantics to match 3.8.x
3) Entrypoint script no longer creates self signed certificates
4) Adds the NOTLS option to start with SSL disabled
### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2021-11-29 11:37 UTC, blankdots commented on entrypoint.sh
> +													{uris, ["amqp:///${MQ_VHOST:-}"]},
is there an extra `/` after all `amqp` ?

2021-11-29 11:37 UTC, blankdots commented on entrypoint.sh
> +	echo "Disabeling TLS"
```suggestion
	echo "Disabling TLS"
```

2021-11-29 12:10 UTC, blankdots approved these changes

2021-11-29 18:03 UTC, blankdots requested changes
just noticed: https://github.com/neicnordic/sda-mq/blob/master/README.md?plain=1#L3 might require a change as well

2021-11-29 18:43 UTC, blankdots approved these changes
LGTM

not sure we want to remove `hooks` folder with this or another PR

2021-11-30 08:09 UTC, dbampalikis approved these changes
Looks good, although I didn't test it

2021-11-30 13:19 UTC, norling approved these changes
Didn't figure out how test it, but as far as I can tell it looks good!

2021-11-30 13:19 UTC, merged