Shovel messages from files.verified
neicnordic/sda-mq pull request #7
Opened 2020-06-22 15:34 UTC by jonandernovella

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

We should now shovel messages from the verified queue instead of completed.
### Changes made:

The MQ configuration now points to verified.

2020-06-23 13:46 UTC, dtitov requested changes

2020-06-23 13:46 UTC, dtitov commented on entrypoint.sh
> -                  {routing_key, <<"completed">>}
This doesn't seem to be correct. If I understood your changes correctly, in the existing `cega_completion` shovel you just replaced the routing keys from `files.completed` to `files.verified`. But we still need to shovel completion message to CEGA (the last step in the data flow: https://localega.readthedocs.io/en/latest/_images/amqp-ping-pong.png). So we can't just change `cega_completion` - we need to keep it as it is now, but additionally introduce similar shovel called `cega_verification` that will separately shovel the verification messages.

2020-06-23 13:46 UTC, dtitov commented on entrypoint.sh
> -                {routing_key, <<"files.completed">>}
See above.

2020-06-23 13:46 UTC, dtitov commented on entrypoint.sh
> -      "name": "files.completed",
See above.

2020-06-24 05:30 UTC, blankdots commented on entrypoint.sh
> -                  {routing_key, <<"completed">>}
so we just add another shovel for `file.verified`

2020-06-24 08:24 UTC, blankdots approved these changes

2020-06-24 09:52 UTC, dtitov approved these changes

2020-06-25 08:29 UTC, merged